import type { BrandingShape } from "./_branding";

export type DesignPreset = {
  id: string;
  name: string;
  tagline: string;
  branding: Required<
    Pick<
      BrandingShape,
      | "primary_color"
      | "secondary_color"
      | "accent_color"
      | "brand_gradient"
      | "background_color"
      | "background_gradient"
      | "background_pattern"
      | "background_pattern_strength"
      | "heading_font"
      | "body_font"
      | "heading_scale"
      | "body_scale"
      | "heading_weight"
      | "body_weight"
      | "heading_letter_spacing"
      | "body_letter_spacing"
      | "heading_line_height"
      | "body_line_height"
      | "icon_scale_feature"
      | "icon_scale_nav"
    >
  >;
};

export const DESIGN_PRESETS: DesignPreset[] = [
  {
    id: "sunset-lakehouse",
    name: "Sunset Lakehouse",
    tagline: "Warm teal & gold",
    branding: {
      primary_color: "#002927",
      secondary_color: "#d4a23a",
      accent_color: "#e8c36a",
      brand_gradient: null,
      background_color: "#faf6ef",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0.12,
      heading_font: "Fraunces",
      body_font: "Montserrat",
      heading_scale: 1,
      body_scale: 1,
      heading_weight: 500,
      body_weight: 400,
      heading_letter_spacing: -0.015,
      body_letter_spacing: 0,
      heading_line_height: 1.15,
      body_line_height: 1.62,
      icon_scale_feature: 1,
      icon_scale_nav: 1,
    },
  },
  {
    id: "coastal-calm",
    name: "Coastal Calm",
    tagline: "Soft navy & sand",
    branding: {
      primary_color: "#1e3a5f",
      secondary_color: "#b8a37a",
      accent_color: "#e9d8a6",
      brand_gradient: null,
      background_color: "#f3f7fa",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0.1,
      heading_font: "Cormorant Garamond",
      body_font: "Inter",
      heading_scale: 1.1,
      body_scale: 1,
      heading_weight: 500,
      body_weight: 400,
      heading_letter_spacing: -0.01,
      body_letter_spacing: 0,
      heading_line_height: 1.2,
      body_line_height: 1.7,
      icon_scale_feature: 1,
      icon_scale_nav: 1,
    },
  },
  {
    id: "mountain-cabin",
    name: "Mountain Cabin",
    tagline: "Forest & amber",
    branding: {
      primary_color: "#2d4a2a",
      secondary_color: "#b4612d",
      accent_color: "#d9985a",
      brand_gradient: null,
      background_color: "#f5ebd9",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0.12,
      heading_font: "Playfair Display",
      body_font: "Lora",
      heading_scale: 1.05,
      body_scale: 1,
      heading_weight: 600,
      body_weight: 400,
      heading_letter_spacing: -0.01,
      body_letter_spacing: 0,
      heading_line_height: 1.18,
      body_line_height: 1.65,
      icon_scale_feature: 1.05,
      icon_scale_nav: 1,
    },
  },
  {
    id: "modern-minimal",
    name: "Modern Minimal",
    tagline: "Clean charcoal",
    branding: {
      primary_color: "#1a1a1a",
      secondary_color: "#6b6b66",
      accent_color: "#c9b896",
      brand_gradient: null,
      background_color: "#ffffff",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Inter",
      body_font: "Inter",
      heading_scale: 1,
      body_scale: 0.95,
      heading_weight: 700,
      body_weight: 400,
      heading_letter_spacing: -0.02,
      body_letter_spacing: 0,
      heading_line_height: 1.1,
      body_line_height: 1.55,
      icon_scale_feature: 0.95,
      icon_scale_nav: 0.95,
    },
  },
  {
    id: "boho-garden",
    name: "Boho Garden",
    tagline: "Terracotta & sage",
    branding: {
      primary_color: "#8b4836",
      secondary_color: "#7a8c66",
      accent_color: "#d9b08c",
      brand_gradient: null,
      background_color: "#eaf0e6",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0.1,
      heading_font: "Cormorant Garamond",
      body_font: "Karla",
      heading_scale: 1.15,
      body_scale: 1,
      heading_weight: 500,
      body_weight: 400,
      heading_letter_spacing: 0,
      body_letter_spacing: 0.005,
      heading_line_height: 1.18,
      body_line_height: 1.7,
      icon_scale_feature: 1,
      icon_scale_nav: 1,
    },
  },
  {
    id: "urban-loft",
    name: "Urban Loft",
    tagline: "Industrial brass",
    branding: {
      primary_color: "#0d0d0d",
      secondary_color: "#a67c2e",
      accent_color: "#d4a857",
      brand_gradient: null,
      background_color: "#f5f5f4",
      background_gradient: null,
      background_pattern: "dots",
      background_pattern_strength: 0.08,
      heading_font: "Bebas Neue",
      body_font: "Work Sans",
      heading_scale: 1.2,
      body_scale: 0.95,
      heading_weight: 400,
      body_weight: 400,
      heading_letter_spacing: 0.04,
      body_letter_spacing: 0.01,
      heading_line_height: 1.05,
      body_line_height: 1.6,
      icon_scale_feature: 1,
      icon_scale_nav: 1,
    },
  },
  {
    id: "mediterranean",
    name: "Mediterranean",
    tagline: "Cobalt & ochre",
    branding: {
      primary_color: "#1d3461",
      secondary_color: "#c8961f",
      accent_color: "#f0c674",
      brand_gradient: null,
      background_color: "#fbf4ee",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0.12,
      heading_font: "DM Serif Display",
      body_font: "DM Sans",
      heading_scale: 1.1,
      body_scale: 1,
      heading_weight: 400,
      body_weight: 400,
      heading_letter_spacing: -0.015,
      body_letter_spacing: 0,
      heading_line_height: 1.15,
      body_line_height: 1.65,
      icon_scale_feature: 1,
      icon_scale_nav: 1,
    },
  },
  {
    id: "nordic-retreat",
    name: "Nordic Retreat",
    tagline: "Soft slate, airy",
    branding: {
      primary_color: "#3a4a52",
      secondary_color: "#b87f3a",
      accent_color: "#e8c887",
      brand_gradient: null,
      background_color: "#fafaf9",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Fraunces",
      body_font: "Inter",
      heading_scale: 1.05,
      body_scale: 1,
      heading_weight: 500,
      body_weight: 400,
      heading_letter_spacing: -0.02,
      body_letter_spacing: 0,
      heading_line_height: 1.2,
      body_line_height: 1.75,
      icon_scale_feature: 0.95,
      icon_scale_nav: 0.95,
    },
  },
  {
    id: "tropical-resort",
    name: "Tropical Resort",
    tagline: "Emerald & coral",
    branding: {
      primary_color: "#064e3b",
      secondary_color: "#d97757",
      accent_color: "#f4b27a",
      brand_gradient: null,
      background_color: "#fbf4ee",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0.12,
      heading_font: "Playfair Display",
      body_font: "Nunito",
      heading_scale: 1.1,
      body_scale: 1,
      heading_weight: 600,
      body_weight: 400,
      heading_letter_spacing: -0.01,
      body_letter_spacing: 0,
      heading_line_height: 1.15,
      body_line_height: 1.65,
      icon_scale_feature: 1.05,
      icon_scale_nav: 1,
    },
  },
  {
    id: "desert-dunes",
    name: "Desert Dunes",
    tagline: "Sienna & olive",
    branding: {
      primary_color: "#8a3a1c",
      secondary_color: "#7a6a3e",
      accent_color: "#d9a878",
      brand_gradient: null,
      background_color: "#f5ebd9",
      background_gradient: null,
      background_pattern: "noise",
      background_pattern_strength: 0.1,
      heading_font: "Cormorant Garamond",
      body_font: "Work Sans",
      heading_scale: 1.1,
      body_scale: 1,
      heading_weight: 500,
      body_weight: 400,
      heading_letter_spacing: 0,
      body_letter_spacing: 0,
      heading_line_height: 1.18,
      body_line_height: 1.65,
      icon_scale_feature: 1,
      icon_scale_nav: 1,
    },
  },
  {
    id: "editorial",
    name: "Editorial",
    tagline: "Newspaper, dense body",
    branding: {
      primary_color: "#18181b",
      secondary_color: "#c4a55d",
      accent_color: "#e6c887",
      brand_gradient: null,
      background_color: "#fdfcfa",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Playfair Display",
      body_font: "Source Serif 4",
      heading_scale: 1.4,
      body_scale: 0.95,
      heading_weight: 700,
      body_weight: 400,
      heading_letter_spacing: -0.025,
      body_letter_spacing: 0,
      heading_line_height: 1.05,
      body_line_height: 1.55,
      icon_scale_feature: 0.9,
      icon_scale_nav: 0.9,
    },
  },
  {
    id: "bold-brutalist",
    name: "Bold Brutalist",
    tagline: "Loud, uppercase",
    branding: {
      primary_color: "#000000",
      secondary_color: "#f59e0b",
      accent_color: "#fbbf24",
      brand_gradient: null,
      background_color: "#ffffff",
      background_gradient: null,
      background_pattern: "grid",
      background_pattern_strength: 0.06,
      heading_font: "Anton",
      body_font: "Inter",
      heading_scale: 1.6,
      body_scale: 1,
      heading_weight: 400,
      body_weight: 500,
      heading_letter_spacing: 0.02,
      body_letter_spacing: 0,
      heading_line_height: 1.05,
      body_line_height: 1.55,
      icon_scale_feature: 1.3,
      icon_scale_nav: 1.15,
    },
  },
  {
    id: "soft-pastel",
    name: "Soft Pastel",
    tagline: "Gentle, light",
    branding: {
      primary_color: "#7c6b8e",
      secondary_color: "#e8a09d",
      accent_color: "#f6c2b6",
      brand_gradient: null,
      background_color: "#fbf6f3",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Quicksand",
      body_font: "Quicksand",
      heading_scale: 1.05,
      body_scale: 1,
      heading_weight: 500,
      body_weight: 400,
      heading_letter_spacing: 0,
      body_letter_spacing: 0.005,
      heading_line_height: 1.25,
      body_line_height: 1.85,
      icon_scale_feature: 0.85,
      icon_scale_nav: 0.9,
    },
  },
  {
    id: "vintage-print",
    name: "Vintage Print",
    tagline: "Old-book feel",
    branding: {
      primary_color: "#3e2c1c",
      secondary_color: "#8b6f47",
      accent_color: "#c9a96e",
      brand_gradient: null,
      background_color: "#f1e8d4",
      background_gradient: null,
      background_pattern: "noise",
      background_pattern_strength: 0.12,
      heading_font: "Libre Baskerville",
      body_font: "EB Garamond",
      heading_scale: 1.15,
      body_scale: 1.05,
      heading_weight: 700,
      body_weight: 400,
      heading_letter_spacing: 0,
      body_letter_spacing: 0.005,
      heading_line_height: 1.18,
      body_line_height: 1.75,
      icon_scale_feature: 1.05,
      icon_scale_nav: 1,
    },
  },
  {
    id: "tech-startup",
    name: "Tech Startup",
    tagline: "Crisp & tight",
    branding: {
      primary_color: "#0a0a0a",
      secondary_color: "#10b981",
      accent_color: "#6ee7b7",
      brand_gradient: null,
      background_color: "#fafafa",
      background_gradient: null,
      background_pattern: "dots",
      background_pattern_strength: 0.05,
      heading_font: "Inter",
      body_font: "Inter",
      heading_scale: 1.1,
      body_scale: 0.95,
      heading_weight: 700,
      body_weight: 400,
      heading_letter_spacing: -0.03,
      body_letter_spacing: -0.005,
      heading_line_height: 1.1,
      body_line_height: 1.55,
      icon_scale_feature: 0.9,
      icon_scale_nav: 0.9,
    },
  },
  {
    id: "royal-mahogany",
    name: "Royal Mahogany",
    tagline: "Rich burgundy",
    branding: {
      primary_color: "#5a1a1a",
      secondary_color: "#a67c2e",
      accent_color: "#c9a358",
      brand_gradient: null,
      background_color: "#f7f0e6",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Cinzel",
      body_font: "Crimson Pro",
      heading_scale: 1.05,
      body_scale: 1.05,
      heading_weight: 600,
      body_weight: 400,
      heading_letter_spacing: 0.05,
      body_letter_spacing: 0,
      heading_line_height: 1.2,
      body_line_height: 1.7,
      icon_scale_feature: 1.1,
      icon_scale_nav: 1,
    },
  },
  {
    id: "garden-wedding",
    name: "Garden Wedding",
    tagline: "Romantic, airy",
    branding: {
      primary_color: "#4a5d3a",
      secondary_color: "#d4a574",
      accent_color: "#f0d4a5",
      brand_gradient: null,
      background_color: "#fef9f0",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Cormorant Garamond",
      body_font: "Karla",
      heading_scale: 1.3,
      body_scale: 1,
      heading_weight: 400,
      body_weight: 400,
      heading_letter_spacing: 0.01,
      body_letter_spacing: 0,
      heading_line_height: 1.18,
      body_line_height: 1.85,
      icon_scale_feature: 1,
      icon_scale_nav: 1,
    },
  },
  {
    id: "cozy-cottage",
    name: "Cozy Cottage",
    tagline: "Warm, chunky",
    branding: {
      primary_color: "#6b3a1a",
      secondary_color: "#c97c3a",
      accent_color: "#e6a368",
      brand_gradient: null,
      background_color: "#fbf0e0",
      background_gradient: null,
      background_pattern: "noise",
      background_pattern_strength: 0.08,
      heading_font: "Fraunces",
      body_font: "Lora",
      heading_scale: 1.1,
      body_scale: 1.05,
      heading_weight: 600,
      body_weight: 400,
      heading_letter_spacing: -0.01,
      body_letter_spacing: 0,
      heading_line_height: 1.18,
      body_line_height: 1.7,
      icon_scale_feature: 1.2,
      icon_scale_nav: 1.1,
    },
  },
  {
    id: "industrial-steel",
    name: "Industrial Steel",
    tagline: "Cold, sharp",
    branding: {
      primary_color: "#1e293b",
      secondary_color: "#475569",
      accent_color: "#94a3b8",
      brand_gradient: null,
      background_color: "#f1f5f9",
      background_gradient: null,
      background_pattern: "grid",
      background_pattern_strength: 0.08,
      heading_font: "Oswald",
      body_font: "Lato",
      heading_scale: 1.15,
      body_scale: 0.95,
      heading_weight: 600,
      body_weight: 400,
      heading_letter_spacing: 0.03,
      body_letter_spacing: 0,
      heading_line_height: 1.1,
      body_line_height: 1.55,
      icon_scale_feature: 0.85,
      icon_scale_nav: 0.85,
    },
  },
  {
    id: "sun-bleached",
    name: "Sun-bleached",
    tagline: "Faded coastal",
    branding: {
      primary_color: "#4a5d6e",
      secondary_color: "#c4a875",
      accent_color: "#e8d4a8",
      brand_gradient: null,
      background_color: "#fbf6ed",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Spectral",
      body_font: "Manrope",
      heading_scale: 1.05,
      body_scale: 1,
      heading_weight: 500,
      body_weight: 400,
      heading_letter_spacing: 0,
      body_letter_spacing: 0,
      heading_line_height: 1.2,
      body_line_height: 1.75,
      icon_scale_feature: 1,
      icon_scale_nav: 1,
    },
  },
  {
    id: "midnight-lounge",
    name: "Midnight Lounge",
    tagline: "Deep navy luxe",
    branding: {
      primary_color: "#1a1f3a",
      secondary_color: "#b89968",
      accent_color: "#d4b478",
      brand_gradient: null,
      background_color: "#f3eee3",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Bodoni Moda",
      body_font: "Karla",
      heading_scale: 1.15,
      body_scale: 1,
      heading_weight: 500,
      body_weight: 400,
      heading_letter_spacing: -0.005,
      body_letter_spacing: 0,
      heading_line_height: 1.15,
      body_line_height: 1.7,
      icon_scale_feature: 1,
      icon_scale_nav: 1,
    },
  },
  {
    id: "provence-lavender",
    name: "Provence",
    tagline: "Soft French",
    branding: {
      primary_color: "#5a4e7c",
      secondary_color: "#b58c5f",
      accent_color: "#d4b888",
      brand_gradient: null,
      background_color: "#f3eef5",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Cormorant Garamond",
      body_font: "Cardo",
      heading_scale: 1.2,
      body_scale: 1,
      heading_weight: 500,
      body_weight: 400,
      heading_letter_spacing: 0,
      body_letter_spacing: 0,
      heading_line_height: 1.2,
      body_line_height: 1.75,
      icon_scale_feature: 1,
      icon_scale_nav: 1,
    },
  },
  {
    id: "big-bold",
    name: "Big & Bold",
    tagline: "Maximum impact",
    branding: {
      primary_color: "#0d1b2a",
      secondary_color: "#fb923c",
      accent_color: "#fdba74",
      brand_gradient: null,
      background_color: "#fffbf5",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Archivo Black",
      body_font: "Work Sans",
      heading_scale: 1.8,
      body_scale: 1,
      heading_weight: 400,
      body_weight: 500,
      heading_letter_spacing: -0.04,
      body_letter_spacing: 0,
      heading_line_height: 1.0,
      body_line_height: 1.6,
      icon_scale_feature: 1.4,
      icon_scale_nav: 1.2,
    },
  },
  {
    id: "whisper-light",
    name: "Whisper Light",
    tagline: "Ultra-light, airy",
    branding: {
      primary_color: "#2b3a47",
      secondary_color: "#6b8a9a",
      accent_color: "#c8d4dc",
      brand_gradient: null,
      background_color: "#ffffff",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Outfit",
      body_font: "Outfit",
      heading_scale: 1.25,
      body_scale: 0.95,
      heading_weight: 300,
      body_weight: 300,
      heading_letter_spacing: 0.04,
      body_letter_spacing: 0.01,
      heading_line_height: 1.3,
      body_line_height: 1.9,
      icon_scale_feature: 0.75,
      icon_scale_nav: 0.8,
    },
  },
  {
    id: "hospitality-classic",
    name: "Hospitality",
    tagline: "Timeless hotel",
    branding: {
      primary_color: "#1a2e4a",
      secondary_color: "#b08a3e",
      accent_color: "#d9b86e",
      brand_gradient: null,
      background_color: "#fbf9f4",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Marcellus",
      body_font: "Open Sans",
      heading_scale: 1.1,
      body_scale: 1,
      heading_weight: 400,
      body_weight: 400,
      heading_letter_spacing: 0.02,
      body_letter_spacing: 0,
      heading_line_height: 1.2,
      body_line_height: 1.65,
      icon_scale_feature: 1,
      icon_scale_nav: 1,
    },
  },
  {
    id: "beach-house",
    name: "Beach House",
    tagline: "Bright & sandy",
    branding: {
      primary_color: "#1565a3",
      secondary_color: "#e8a865",
      accent_color: "#fbd28b",
      brand_gradient: null,
      background_color: "#eef4f8",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Quicksand",
      body_font: "Nunito",
      heading_scale: 1.1,
      body_scale: 1,
      heading_weight: 600,
      body_weight: 400,
      heading_letter_spacing: 0,
      body_letter_spacing: 0,
      heading_line_height: 1.18,
      body_line_height: 1.7,
      icon_scale_feature: 1.15,
      icon_scale_nav: 1.05,
    },
  },
  {
    id: "eclectic-script",
    name: "Eclectic Script",
    tagline: "Handwritten heading",
    branding: {
      primary_color: "#2a1a2e",
      secondary_color: "#c97c3a",
      accent_color: "#e6a868",
      brand_gradient: null,
      background_color: "#f7f1e9",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Caveat",
      body_font: "Inter",
      heading_scale: 1.5,
      body_scale: 1,
      heading_weight: 700,
      body_weight: 400,
      heading_letter_spacing: 0,
      body_letter_spacing: 0,
      heading_line_height: 1.1,
      body_line_height: 1.7,
      icon_scale_feature: 1,
      icon_scale_nav: 1,
    },
  },
  {
    id: "monochrome-premium",
    name: "Monochrome",
    tagline: "Pure black, one accent",
    branding: {
      primary_color: "#000000",
      secondary_color: "#4a4a4a",
      accent_color: "#d4a857",
      brand_gradient: null,
      background_color: "#ffffff",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Inter",
      body_font: "Inter",
      heading_scale: 1.3,
      body_scale: 1,
      heading_weight: 800,
      body_weight: 400,
      heading_letter_spacing: -0.04,
      body_letter_spacing: 0,
      heading_line_height: 1.05,
      body_line_height: 1.6,
      icon_scale_feature: 1.1,
      icon_scale_nav: 1,
    },
  },
  {
    id: "rosy-garden",
    name: "Rosy Garden",
    tagline: "Pink & coral",
    branding: {
      primary_color: "#8b1e3f",
      secondary_color: "#d97757",
      accent_color: "#f4b27a",
      brand_gradient: null,
      background_color: "#fef0f0",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Playfair Display",
      body_font: "Karla",
      heading_scale: 1.2,
      body_scale: 1,
      heading_weight: 500,
      body_weight: 400,
      heading_letter_spacing: -0.01,
      body_letter_spacing: 0,
      heading_line_height: 1.15,
      body_line_height: 1.7,
      icon_scale_feature: 1,
      icon_scale_nav: 1,
    },
  },
  {
    id: "compact-city",
    name: "Compact City",
    tagline: "Dense, urban",
    branding: {
      primary_color: "#1c1c1c",
      secondary_color: "#4a5fc4",
      accent_color: "#8590e8",
      brand_gradient: null,
      background_color: "#f5f5f4",
      background_gradient: null,
      background_pattern: "dots",
      background_pattern_strength: 0.07,
      heading_font: "Space Grotesk",
      body_font: "Inter",
      heading_scale: 0.95,
      body_scale: 0.9,
      heading_weight: 600,
      body_weight: 400,
      heading_letter_spacing: -0.02,
      body_letter_spacing: 0,
      heading_line_height: 1.15,
      body_line_height: 1.5,
      icon_scale_feature: 0.85,
      icon_scale_nav: 0.85,
    },
  },
  {
    id: "alpine-lodge",
    name: "Alpine Lodge",
    tagline: "Tall, crisp & cool",
    branding: {
      primary_color: "#1d3a4a",
      secondary_color: "#8aa6b8",
      accent_color: "#d2e0e8",
      brand_gradient: null,
      background_color: "#f0f4f7",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Bebas Neue",
      body_font: "Hanken Grotesk",
      heading_scale: 1.5,
      body_scale: 1,
      heading_weight: 400,
      body_weight: 400,
      heading_letter_spacing: 0.06,
      body_letter_spacing: 0,
      heading_line_height: 1.0,
      body_line_height: 1.65,
      icon_scale_feature: 0.95,
      icon_scale_nav: 1,
    },
  },
  {
    id: "honey-amber",
    name: "Honey Amber",
    tagline: "Warm, generous icons",
    branding: {
      primary_color: "#5c3a1a",
      secondary_color: "#d4a23a",
      accent_color: "#f5cf78",
      brand_gradient: null,
      background_color: "#fdf6e9",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Yeseva One",
      body_font: "Nunito",
      heading_scale: 1.2,
      body_scale: 1.05,
      heading_weight: 400,
      body_weight: 400,
      heading_letter_spacing: -0.005,
      body_letter_spacing: 0,
      heading_line_height: 1.18,
      body_line_height: 1.75,
      icon_scale_feature: 1.3,
      icon_scale_nav: 1.15,
    },
  },
  {
    id: "stone-zen",
    name: "Stone Zen",
    tagline: "Quiet, balanced",
    branding: {
      primary_color: "#3d3d3a",
      secondary_color: "#8b7d6b",
      accent_color: "#c8b89a",
      brand_gradient: null,
      background_color: "#f3f0eb",
      background_gradient: null,
      background_pattern: "noise",
      background_pattern_strength: 0.08,
      heading_font: "Cormorant Infant",
      body_font: "Mulish",
      heading_scale: 1.15,
      body_scale: 1,
      heading_weight: 500,
      body_weight: 400,
      heading_letter_spacing: 0.005,
      body_letter_spacing: 0,
      heading_line_height: 1.25,
      body_line_height: 1.8,
      icon_scale_feature: 0.9,
      icon_scale_nav: 0.95,
    },
  },
  {
    id: "carnival-pop",
    name: "Carnival Pop",
    tagline: "Loud retro pop",
    branding: {
      primary_color: "#c2185b",
      secondary_color: "#fbc02d",
      accent_color: "#4dd0e1",
      brand_gradient: null,
      background_color: "#fff8e7",
      background_gradient: null,
      background_pattern: "dots",
      background_pattern_strength: 0.1,
      heading_font: "Lobster",
      body_font: "Poppins",
      heading_scale: 1.45,
      body_scale: 1,
      heading_weight: 400,
      body_weight: 500,
      heading_letter_spacing: 0,
      body_letter_spacing: 0,
      heading_line_height: 1.1,
      body_line_height: 1.65,
      icon_scale_feature: 1.2,
      icon_scale_nav: 1.1,
    },
  },
  {
    id: "japandi",
    name: "Japandi",
    tagline: "Minimal east-west",
    branding: {
      primary_color: "#2c2c2c",
      secondary_color: "#a89682",
      accent_color: "#d4c4a8",
      brand_gradient: null,
      background_color: "#f7f4ee",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Noto Sans",
      body_font: "Noto Sans",
      heading_scale: 1.05,
      body_scale: 0.95,
      heading_weight: 500,
      body_weight: 400,
      heading_letter_spacing: 0.06,
      body_letter_spacing: 0.01,
      heading_line_height: 1.4,
      body_line_height: 1.85,
      icon_scale_feature: 0.8,
      icon_scale_nav: 0.85,
    },
  },
  {
    id: "moss-stone",
    name: "Moss & Stone",
    tagline: "Earthy & textured",
    branding: {
      primary_color: "#3a4a2a",
      secondary_color: "#7a6b4a",
      accent_color: "#c4b48c",
      brand_gradient: null,
      background_color: "#eef0e8",
      background_gradient: null,
      background_pattern: "noise",
      background_pattern_strength: 0.15,
      heading_font: "Vollkorn",
      body_font: "Bitter",
      heading_scale: 1.1,
      body_scale: 1,
      heading_weight: 600,
      body_weight: 400,
      heading_letter_spacing: 0,
      body_letter_spacing: 0,
      heading_line_height: 1.18,
      body_line_height: 1.7,
      icon_scale_feature: 1.05,
      icon_scale_nav: 1,
    },
  },
  {
    id: "soft-modern",
    name: "Soft Modern",
    tagline: "Rounded, friendly",
    branding: {
      primary_color: "#3a4d7c",
      secondary_color: "#e8825a",
      accent_color: "#f5b48a",
      brand_gradient: null,
      background_color: "#fafaf7",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Comfortaa",
      body_font: "Rubik",
      heading_scale: 1.1,
      body_scale: 1,
      heading_weight: 600,
      body_weight: 400,
      heading_letter_spacing: -0.005,
      body_letter_spacing: 0,
      heading_line_height: 1.25,
      body_line_height: 1.7,
      icon_scale_feature: 1.05,
      icon_scale_nav: 1,
    },
  },
  {
    id: "warehouse",
    name: "Warehouse",
    tagline: "Heavy slab, gritty",
    branding: {
      primary_color: "#1a1a1a",
      secondary_color: "#c9501c",
      accent_color: "#e89868",
      brand_gradient: null,
      background_color: "#ede9e3",
      background_gradient: null,
      background_pattern: "grid",
      background_pattern_strength: 0.1,
      heading_font: "Alfa Slab One",
      body_font: "Work Sans",
      heading_scale: 1.35,
      body_scale: 0.95,
      heading_weight: 400,
      body_weight: 400,
      heading_letter_spacing: -0.005,
      body_letter_spacing: 0.005,
      heading_line_height: 1.1,
      body_line_height: 1.6,
      icon_scale_feature: 1.2,
      icon_scale_nav: 1.05,
    },
  },
  {
    id: "spa-retreat",
    name: "Spa Retreat",
    tagline: "Calm, generous spacing",
    branding: {
      primary_color: "#3e5a4e",
      secondary_color: "#a8b89c",
      accent_color: "#d8e0c8",
      brand_gradient: null,
      background_color: "#f5f7f0",
      background_gradient: null,
      background_pattern: "none",
      background_pattern_strength: 0,
      heading_font: "Italiana",
      body_font: "Albert Sans",
      heading_scale: 1.35,
      body_scale: 1,
      heading_weight: 400,
      body_weight: 400,
      heading_letter_spacing: 0.04,
      body_letter_spacing: 0.005,
      heading_line_height: 1.3,
      body_line_height: 1.9,
      icon_scale_feature: 0.85,
      icon_scale_nav: 0.95,
    },
  },
];

/**
 * Match preset against current branding using the load-bearing identity
 * fields. Two presets are considered "the same look" if these align, even if
 * the host has tweaked a slider afterwards.
 */
export function findActivePreset(
  branding: BrandingShape
): DesignPreset | null {
  return (
    DESIGN_PRESETS.find(
      (p) =>
        p.branding.primary_color === branding.primary_color &&
        p.branding.secondary_color === branding.secondary_color &&
        p.branding.accent_color === branding.accent_color &&
        p.branding.background_color === branding.background_color &&
        p.branding.heading_font === branding.heading_font &&
        p.branding.body_font === branding.body_font
    ) ?? null
  );
}
